---
abstract: "Enable template toolkit to use Amazon's S3 service as a provier of templates."
author:
  - 'Gautam Dey <gdey@cpan.org>'
build_requires:
  Digest::SHA1: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Provider-Amazon-S3
requires:
  CHI: 0.50
  Data::Dumper: 0
  DateTime: 0
  JSON: 0
  List::MoreUtils: 0
  Net::Amazon::S3::Client: 0
  Template::Provider: 0
  Try::Tiny: 0
  base: 0
  feature: 0
  perl: 5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Template-Provider-Amazon-S3
  homepage: https://github.com/gdey/Template-Provider-Amazon-S3-/wiki
  repository: git://github.com/gdey/template-provider-amazon-s3.git
version: 0.009
